http:
  routers:
    # Route pour le PC 1
    router-srv1:
      rule: "Host(`srv1.releveant.projet.filiere.info`)"
      service: "service-srv1"
      entryPoints: ["web"]

    # Route pour le PC 2
    router-pc1:
      rule: "Host(`pc1.releveant.projet.filiere.info`)"
      service: "service-pc1"
      entryPoints: ["web"]

     # Route pour le PC 3
    router-pc2:
      rule: "Host(`pc2.releveant.projet.filiere.info`)"
      service: "service-pc2"
      entryPoints: ["web"]

     # Route pour le hub
    router-hub:
      rule: "Host(`hub.releveant.projet.filiere.info`)"
      service: "service-hub"
      entryPoints: ["web"]

  services:
    service-srv1:
      loadBalancer:
        servers:
          - url: "http://10.4.244.93:8080"

    service-pc1:
      loadBalancer:
        servers:
          - url: "http://10.4.247.178:8080"

    service-pc2:
      loadBalancer:
        servers:
          - url: "http://10.4.253.120:8080"

    service-hub:
      loadBalancer:
        servers:
          - url: "http://10.4.244.86:8888"